#spring:
#  application:
#    name: eureka-server
##    version:test
#
#    # (nested)
#    # more readable
#    # string, boolean, number
#    # lightweight
#    # list (-)

server:
  port: 8761

eureka:
  client:
#   a server should not register itself as a service (client)
    register-with-eureka: false
#   prevent fetching its own service list
    fetch-registry: false